load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "hash_set",
    srcs = ["hash_set.c"],
    hdrs = ["hash_set.h"],
    deps = [],
)
