load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

package(default_visibility = ["//visibility:private"])

cc_binary(
    name = "string_intern_example",
    srcs = ["string_intern_example.c"],
    deps = ["@intern//intern"],
)
